/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class libjniNewtonRaphson_JavaNewtonRaphson */

#ifndef _Included_libjniNewtonRaphson_JavaNewtonRaphson
#define _Included_libjniNewtonRaphson_JavaNewtonRaphson
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     libjniNewtonRaphson_JavaNewtonRaphson
 * Method:    ejecutarNewtonRaphson
 * Signature: (IDID)V
 */
JNIEXPORT void JNICALL Java_libjniNewtonRaphson_JavaNewtonRaphson_ejecutarNewtonRaphson
  (JNIEnv *, jobject, jint, jdouble, jint, jdouble);

#ifdef __cplusplus
}
#endif
#endif
